export const SET_CATEGORIES = 'SET_CATEGORIES';
export const MOVE_CATEGORIES = 'MOVE_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const MOVE_ITEMS = 'MOVE_ITEMS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CATEGORY_DIALOG = 'TOGGLE_CATEGORY_DIALOG';
export const TOGGLE_ITEM_DIALOG = 'TOGGLE_ITEM_DIALOG';






